services:
  app:
    image: anhquoc09/shopco-laravel:latest
    container_name: shopco_app
    restart: always
    env_file: .env
    ports:
      - "80:80"
    volumes:
      - storage_data:/var/www/html/storage
    depends_on:
      - shopco_db
    networks:
      - shopco-network

  worker:
    image: anhquoc09/shopco-laravel:latest
    container_name: shopco_worker
    command: php artisan queue:work
    user: "www-data"
    env_file: .env
    volumes:
      - storage_data:/var/www/html/storage
    depends_on:
      - shopco_db
    networks:
      - shopco-network

  shopco_db:
    image: mysql:8.0.45-debian
    container_name: shopco_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
    command:
      - --default-authentication-plugin=mysql_native_password
      - --skip-name-resolve
      - --performance-schema=OFF
      - --innodb-buffer-pool-size=64M
    ports:
      - "3306:3306"
    volumes:
      - shopco-db-data:/var/lib/mysql
    networks:
      - shopco-network

volumes:
  shopco-db-data:
  storage_data:

networks:
  shopco-network: