name: Deploy Laravel to EC2

on:
  push:
    branches:
      - main # Detect new code in main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/shopco-laravel:latest

  deploy-to-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Action 1: Transfer docker-compose.prod.ymal from GitHub to EC2
      - name: Copy compose file to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.prod.ymal"
          target: "/home/ubuntu/shopco-laravel" # Project folder on EC2

      # Action 2: SSH into EC2, pull new Image, and run
      - name: Execute deployment on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/shopco-laravel
            # Pull new image from Docker Hub
            docker-compose -f docker-compose.prod.ymal pull
            # Restart container with new image
            docker-compose -f docker-compose.prod.ymal up -d
            # Run migration if there are changes in DB
            docker-compose -f docker-compose.prod.ymal exec -T app php artisan migrate --force
